--- # server port config (dynamically allocate)
server:
     port: 3000

security:
    user:
        password: password
--- # application
spring:
    application:
        name : ui-server
    resources:
      static-locations: classpath:/client/
